services:

  database:
    container_name: mysql-database
    image: 'mysql:latest'
    ports:
      - "3366:3306"
    restart: always
    environment:
      MYSQL_DATABASE: "springbootuser"
      MYSQL_USER: "springmicroserviceuser"
      MYSQL_PASSWORD: "111111"
      MYSQL_ROOT_PASSWORD: "111111"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: "mysql -u $MYSQL_USER --password=$MYSQL_ROOT_PASSWORD content -e 'select 1'"
      interval: 1s
      retries: 120

  configserver:
    image: configserver
    container_name: configServer
    build:
      context: ./configserver
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    networks:
      backend:
        aliases:
          - "configserver"

  eurekaserver:
    image: eurekaserver
    ports:
      - "8761:8761"
    build:
      context: ./discoveryserver
      dockerfile: Dockerfile
    depends_on:
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"


  gatewayserver:
    image: gatewayserver
    ports:
      - "8600:8600"
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      PROFILE: "default"
      SERVER_PORT: "8600"
      CONFIGSERVER_URI: "http://configserver:9191"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_PORT: "9191"
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway"

  userservice:
    image: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      CONFIGSERVER_URI: "http://configserver:9191"
      CONFIGSERVER_PORT: "9191"
      DATABASESERVER_PORT: "3306"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "9000:9000"
    networks:
      - backend

  managementservice:
    image: management-service
    build:
      context: ./management-service
      dockerfile: Dockerfile
    environment:
      CONFIGSERVER_URI: "http://configserver:9191"
      CONFIGSERVER_PORT: "9191"
      DATABASESERVER_PORT: "3306"
    depends_on:
      configserver:
        condition: service_started
    ports:
      - "9002:9002"
    networks:
      - backend

  advertisementservice:
    image: advertisement-service
    build:
      context: ./advertisement-service
      dockerfile: Dockerfile
    environment:
      CONFIGSERVER_URI: "http://configserver:9191"
      CONFIGSERVER_PORT: "9191"
      DATABASESERVER_PORT: "3306"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "9001:9001"
    networks:
      - backend


  reportservice:
    image: report-service
    build:
      context: ./report-service
      dockerfile: Dockerfile
    environment:
      CONFIGSERVER_URI: "http://configserver:9191"
      CONFIGSERVER_PORT: "9191"
      DATABASESERVER_PORT: "3306"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "9003:9003"
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8181:8080"
    networks:
      backend:
        aliases:
          - "keycloak"
    command:
      - start-dev

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rmq3"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "123456"
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  backend:
    driver: bridge


volumes:
  db-data:
